Repository hanghae99-MiniProject/Front-end, pull requests merged in 2022-10, with the labels that each got.

#12 chore: Router와 Pages 연결
  package.json
  src/App.js
  src/components/joinform/JoinForm.jsx
  src/components/movieinfo/style.js
  src/components/reviewinfo/ReviewInfo.jsx
  src/components/reviewinfo/style.js
  src/components/reviewlist/ReviewList.jsx
  src/components/reviewthumb/ReviewThumb.jsx
  src/components/reviewthumb/style.js
  src/index.css
  src/index.js
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/Review.jsx
  src/pages/Write.jsx
  src/shared/Router.jsx
Labels: documentation

#13 Header, Logo, write, Router 수정
  src/components/header/style.js
  src/image/logo.png
  src/pages/Detail.jsx
  src/pages/Write.jsx
  src/shared/Router.jsx
Labels: bug, enhancement

#15 feat: 글쓰기 버튼 생성
  src/components/buttonwrite/ButtonWrite.jsx
  src/components/buttonwrite/style.js
  src/components/joinform/JoinForm.jsx
  src/image/createicon.png
Labels: enhancement

#18 chore: Join, Login API 연결
  src/components/joinform/JoinForm.jsx
  src/components/loginform/LoginForm.jsx
Labels: enhancement

#19 chore: BE API 연결
  src/components/header/Header.jsx
  src/components/joinform/JoinForm.jsx
  src/components/loginform/LoginForm.jsx
  src/pages/Review.jsx
Labels: enhancement

#21 Feat: Detail,Write components 추가
  src/components/detailInfo/DetailInfo.jsx
  src/components/reviewWrite/ReviewWrite.jsx
  src/pages/Detail.jsx
  src/pages/Write.jsx
  src/redux/modules/writeSlice.js
Labels: enhancement

#22 fea: logout 추가, login 시에만 write 페이지 접속할 수 있도록 조건 변경
  src/components/header/Header.jsx
  src/pages/Write.jsx
Labels: bug, enhancement

#23 feat: Main BE API 연결 / fix: reviewID API와 변수명 통일
  src/components/reviewlist/ReviewList.jsx
  src/components/reviewthumb/ReviewThumb.jsx
  src/pages/Main.jsx
Labels: bug, enhancement

#24 feat: Loading 컴포넌트 추가 및 Main, Review 페이지에 추가
  src/components/header/Header.jsx
  src/components/header/style.js
  src/components/loading/Loading.jsx
  src/components/loading/style.css
  src/components/loginform/LoginForm.jsx
  src/components/reviewthumb/ReviewThumb.jsx
  src/pages/Main.jsx
  src/pages/Review.jsx
  src/redux/modules/writeSlice.js
Labels: bug, enhancement

#25 fix : Detail 페이지 내용 수정
  src/components/detailInfo/DetailInfo.jsx
  src/components/movieinfo/MovieInfo.jsx
Labels: documentation

#26 chore: API URL 환경변수로 변경 / feat: Heart 추가
  .env
  src/components/header/Header.jsx
  src/components/heart/Heart.jsx
  src/components/heart/style.js
  src/components/joinform/JoinForm.jsx
  src/components/loginform/LoginForm.jsx
  src/image/heart-regular.svg
  src/image/heart-solid.svg
  src/pages/Main.jsx
  src/shared/Request.jsx
Labels: enhancement

#27 fix : .env 적용
  src/components/reviewWrite/ReviewWrite.jsx
  src/redux/modules/writeSlice.js
Labels: enhancement

#29 feat : 삭제로직 추가
  src/components/comment/Comment.jsx
Labels: enhancement

#30 feat: comment 추가
  src/components/comment/Comment.jsx
  src/components/detailInfo/DetailInfo.jsx
Labels: enhancement

#31 feat: Heart action update & Movie Component 에 Heart Component 추가
  src/components/heart/Heart.jsx
  src/components/heart/style.js
  src/components/movieinfo/MovieInfo.jsx
  src/components/reviewinfo/ReviewInfo.jsx
Labels: enhancement

#32 fix : Detail page 댓글 추가
  src/components/detailInfo/DetailInfo.jsx
  src/components/reviewWrite/ReviewWrite.jsx
  src/redux/modules/writeSlice.js
Labels: enhancement

#35 fix: Review List에서 하트 갯수, 코멘트 갯수 추가
  src/components/reviewthumb/ReviewThumb.jsx
Labels: bug

#36 fix: 일부 경로에서 token 삭제가 안되는 경우 수정 / fix: 리뷰 수정/삭제버튼 본인 게시글이 아닐 경우 노출되지 않도록 수정
  src/components/detailInfo/DetailInfo.jsx
  src/components/header/Header.jsx
Labels: bug

#37 Heejin
  src/components/comment/Comment.jsx
  src/components/comment/style.js
  src/components/detailInfo/DetailInfo.jsx
  src/components/reviewWrite/ReviewWrite.jsx
  yarn.lock
Labels: documentation

#38 fix: Detail page 접속 시 Token이 2회 저장되는 오류 수정 / 전체 하트가 0개일 때 예외 처리 추가
  src/components/detailInfo/DetailInfo.jsx
  src/components/loginform/LoginForm.jsx
  src/pages/Main.jsx
  src/pages/Review.jsx
Labels: bug

#39 Heejin
  src/components/detailInfo/DetailInfo.jsx
  src/components/loginform/LoginForm.jsx
  src/pages/Main.jsx
  src/pages/Review.jsx
  src/redux/modules/writeSlice.js
Labels: documentation

#40 fix: 하트 갯수 출력 오류 수정 + chore: 이미지 새 창 띄우기
  src/components/heart/Heart.jsx
  src/components/movieinfo/MovieInfo.jsx
Labels: bug, enhancement

#41 fix: 로그아웃 상태에서 댓글 입력시 로그인페이지로 이동 기능 추가
  src/components/comment/Comment.jsx
Labels: documentation

#42 feat: dropdown menu 추가
  src/components/dropdownmenu/DropDownMenu.jsx
  src/components/dropdownmenu/style.js
  src/components/header/Header.jsx
Labels: enhancement

#45 Heejin
  src/components/loginform/LoginForm.jsx
  src/components/reviewWrite/ReviewWrite.jsx
  src/pages/Main.jsx
  src/pages/Review.jsx
Labels: documentation
